require_relative '../guess'
require_relative 'player'

class Computer < Player
  def initialize
    super('T300')

    @next_guess = nil
    @current_guess = nil
  end

  def make_code
    puts '> Secret code generated by the computer player.'
    "#{rand(1..6)}#{rand(1..6)}#{rand(1..6)}#{rand(1..6)}"
  end

  def make_guess(feedback)
    @next_guess = Guess.new if feedback.nil?

    @current_guess = @next_guess.create_guess(feedback, @current_guess)
    puts "> #{@name} guess: #{@current_guess}"

    @current_guess
  end
end
